In [1]:
#importing the packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import sys
from sklearn.metrics import confusion_matrix

In [2]:
#reading the dataset
s = 'flu_data.csv'
df = pd.read_csv(s)
df.head()

Student  Vaccin  HndWshQual  HndWshFreq  SociDist  NoFaceContact  \
0        1       3           4           4         2              1   
1        2       2           4           4         5              2   
2        3       3           2           2         2              3   
3        4       3           3           2         2              2   
4        5       2           5           3         3              2   

   RespEttiqu  PersnDist  HandSanit   Risk  Complications  Barriers  \
0           5          1          1 -0.770         -1.453     0.000   
1           5          4          4 -0.345          0.000    -0.489   
2           2          2          1 -0.406         -0.575    -0.234   
3           5          3          1 -0.575         -0.197    -0.429   
4           5          5          3  0.000         -0.770     0.097   

   Inefficacy  KnowlTrans  KnowlMgmt  Sick  Flu  Female  
0       0.929      -0.554      0.000   0.0  0.0     1.0  
1       0.149      -0.554      1.482   1.0  0.0     0.0  
2       0.693      -0.182     -1.482   0.0  0.0     0.0  
3       0.000       0.554      0.000   2.0  1.0     NaN  
4       0.546       0.554      0.684   1.0  0.0     0.0

In [8]:
#coding the sigmoid function
def sigmoid(x,parameters):
    hx=np.dot(x,parameters)
    return 1/(1+np.exp(-hx))
#coding the cost function
def costfun(x,y,parameters,m,sigmod):
    y=np.array(y)
    return (-1/m)*np.sum((y*np.log(sigmod))+(1-y)*np.log(1-sigmod))
#coding the logistic regression from scratch
def logisticregression(x,y,lr,parameters,iters,m,lambd):
    costfunctionvalues=[]
    for i in range(iters):
        sigmod=sigmoid(x,parameters)
        #added the regularization to the below function
        gradient = (np.dot(x.T,(sigmod - np.array([y]))))+(lambd*np.sum(parameters)) / m
        parameters=parameters-(lr*gradient).T
        parameters=parameters[0][0]
        costfunctionvalues.append(costfun(x,y,parameters,m,sigmod))
    return parameters
#predicton function for calculating predicted values
def prediction(x,parameters,cuttingvalue):
    value=sigmoid(x,parameters)
    if (value > cuttingvalue) :
        return 1
    else:
        return 0
#calculating the  performance metrics   
def performance(gh,y,d1,parameters,s):
    predicted=[]
    for i in range(s):
        predicted.append(prediction(gh.iloc[[i]],parameters,0.7))       
    yc=d1['Flu']  
    print("confusion matrix")
    print(confusion_matrix(y,predicted) )
    tp=0
    fp=0
    fn=0
    tn=0
    for i in range(s):
        if(yc[i]==1 and predicted[i]==1):
            tp=tp+1
        
        if(yc[i]==0 and predicted[i]==1):
            fp=fp+1
        
        if(yc[i]==1 and predicted[i]==0):
            fn=fn+1
        
        if(yc[i]==0 and predicted[i]==0):
            tn=tn+1    
    print("accuracy")
    if((tp+tn+fp+fn)== 0):
        print("0")
    else:    
        print((tp+tn)/(tp+tn+fp+fn))
    print("precision")    
    if((tp+fp)==0): 
        print("0")
    else:    
        print((tp)/(tp+fp))
    print("recall")    
    if((tp+fn)==0):
        print("0")
    else:    
        print((tp)/(tp+fn))  

In [9]:
key1=['Risk','HndWshQual','HndWshFreq','Flu']
d1=pd.DataFrame(df[key1])
d1.isnull().sum()

Risk           0
HndWshQual     0
HndWshFreq     0
Flu           36
dtype: int64

In [10]:
d1['Flu'].fillna(value=0.0,inplace=True)

In [11]:
#features that got best accuracy in 3c
x=d1[['Risk','HndWshQual','HndWshFreq']]
y=d1[['Flu']]
s=x.shape[0] 
m=x.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
lambd=0.63
parameters=logisticregression(x,y,lr,parameters,iters,s,lambd)
performance(x,y,d1,parameters,s)

confusion matrix
[[327   5]
 [ 72   6]]
accuracy
0.8121951219512196
precision
0.5454545454545454
recall
0.07692307692307693


In [13]:
#feature scaling by minmax scaling
mx=np.max(x)
mi=np.min(x)
xs=(x-mi)/(mx-mi)
parameters=np.ones(m)
parameters=logisticregression(xs,y,lr,parameters,iters,s,lambd)
performance(xs,y,d1,parameters,s)

confusion matrix
[[ 53 279]
 [  0  78]]
accuracy
0.3195121951219512
precision
0.2184873949579832
recall
1.0


In [ ]:
#sigmoid function
def sigmoid(x,parameters):
    hx=np.dot(x,parameters)
    return 1/(1+np.exp(-hx))
#cost function is changed
def costfun(x,y,parameters,m,sigmod):
    y=np.array(y)
    return (-1/(2*m))*np.sum((sigmod-y)*(sigmod-y))
#coding the logistic regression from scratch
def logisticregression(x,y,lr,parameters,iters,m,lambd):
    costfunctionvalues=[]
    for i in range(iters):
        sigmod=sigmoid(x,parameters)
        #added the regularization to the below function
        gradient = (np.dot(x.T,(sigmod - np.array([y]))))+(lambd*np.sum(parameters)) / m
        parameters=parameters-(lr*gradient).T
        parameters=parameters[0][0]
        costfunctionvalues.append(costfun(x,y,parameters,m,sigmod))    
    return parameters
#predicton function for calculating predicted values
def prediction(x,parameters,cuttingvalue):
    value=sigmoid(x,parameters)
    if (value > cuttingvalue) :
        return 1
    else:
        return 0
#calculating the  performance metrics   
def performance(gh,y,d1,parameters,s):
    predicted=[]
    for i in range(s):
        predicted.append(prediction(gh.iloc[[i]],parameters,0.7))       
    yc=d1['Flu']  
    print("confusion matrix")
    print(confusion_matrix(y,predicted) )
    tp=0
    fp=0
    fn=0
    tn=0
    for i in range(s):
        if(yc[i]==1 and predicted[i]==1):
            tp=tp+1
        
        if(yc[i]==0 and predicted[i]==1):
            fp=fp+1
        
        if(yc[i]==1 and predicted[i]==0):
            fn=fn+1
        
        if(yc[i]==0 and predicted[i]==0):
            tn=tn+1    
    print("accuracy")
    if((tp+tn+fp+fn)== 0):
        print("0")
    else:    
        print((tp+tn)/(tp+tn+fp+fn))
    print("precision")    
    if((tp+fp)==0): 
        print("0")
    else:    
        print((tp)/(tp+fp))
    print("recall")    
    if((tp+fn)==0):
        print("0")
    else:    
        print((tp)/(tp+fn))  

In [15]:
parameters=np.ones(m)
parameters=logisticregression(x,y,lr,parameters,iters,s,lambd)
performance(x,y,d1,parameters,s)

confusion matrix
[[327   5]
 [ 72   6]]
accuracy
0.8121951219512196
precision
0.5454545454545454
recall
0.07692307692307693
