In [1]:
#importing the packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import sys
from sklearn.metrics import confusion_matrix

In [2]:
#reading the dataset
s = 'flu_data.csv'
df = pd.read_csv(s)
df.head()

Student  Vaccin  HndWshQual  HndWshFreq  SociDist  NoFaceContact  \
0        1       3           4           4         2              1   
1        2       2           4           4         5              2   
2        3       3           2           2         2              3   
3        4       3           3           2         2              2   
4        5       2           5           3         3              2   

   RespEttiqu  PersnDist  HandSanit   Risk  Complications  Barriers  \
0           5          1          1 -0.770         -1.453     0.000   
1           5          4          4 -0.345          0.000    -0.489   
2           2          2          1 -0.406         -0.575    -0.234   
3           5          3          1 -0.575         -0.197    -0.429   
4           5          5          3  0.000         -0.770     0.097   

   Inefficacy  KnowlTrans  KnowlMgmt  Sick  Flu  Female  
0       0.929      -0.554      0.000   0.0  0.0     1.0  
1       0.149      -0.554      1.482   1.0  0.0     0.0  
2       0.693      -0.182     -1.482   0.0  0.0     0.0  
3       0.000       0.554      0.000   2.0  1.0     NaN  
4       0.546       0.554      0.684   1.0  0.0     0.0

In [3]:
#coding the sigmoid function
def sigmoid(x,parameters):
    hx=np.dot(x,parameters)
    return 1/(1+np.exp(-hx))
#coding the cost function
def costfun(x,y,parameters,m,sigmod):
    y=np.array(y)
    return (-1/m)*np.sum((y*np.log(sigmod))+(1-y)*np.log(1-sigmod))
#coding the logistic regression from scratch
def logisticregression(x,y,lr,parameters,iters,m):
    costfunctionvalues=[]
    for i in range(iters):
        sigmod=sigmoid(x,parameters)
        gradient = np.dot(x.T,(sigmod - np.array([y]))) / m
        parameters=parameters-(lr*gradient).T
        parameters=parameters[0][0]
        costfunctionvalues.append(costfun(x,y,parameters,m,sigmod))
    return parameters
#predicton function for calculating predicted values
def prediction(x,parameters,cuttingvalue):
    value=sigmoid(x,parameters)
    if (value > cuttingvalue) :
        return 1
    else:
        return 0
#calculating the  performance metrics   
def performance(gh,y,d1,parameters,s):
    predicted=[]
    for i in range(s):
        predicted.append(prediction(gh.iloc[[i]],parameters,0.7))       
    yc=d1['Flu']  
    print("confusion matrix")
    print(confusion_matrix(y,predicted) )
    tp=0
    fp=0
    fn=0
    tn=0
    for i in range(s):
        if(yc[i]==1 and predicted[i]==1):
            tp=tp+1
        
        if(yc[i]==0 and predicted[i]==1):
            fp=fp+1
        
        if(yc[i]==1 and predicted[i]==0):
            fn=fn+1
        
        if(yc[i]==0 and predicted[i]==0):
            tn=tn+1    
    print("accuracy")
    if((tp+tn+fp+fn)== 0):
        print("0")
    else:    
        print((tp+tn)/(tp+tn+fp+fn))
    print("precision")    
    if((tp+fp)==0): 
        print("0")
    else:    
        print((tp)/(tp+fp))
    print("recall")    
    if((tp+fn)==0):
        print("0")
    else:    
        print((tp)/(tp+fn))  

In [4]:
key1=['Vaccin','HndWshQual','HndWshFreq','SociDist','NoFaceContact','RespEttiqu','PersnDist','HandSanit','Risk','Inefficacy','KnowlTrans','KnowlMgmt','Flu']
d1=pd.DataFrame(df[key1])
d1.isnull().sum()

Vaccin            0
HndWshQual        0
HndWshFreq        0
SociDist          0
NoFaceContact     0
RespEttiqu        0
PersnDist         0
HandSanit         0
Risk              0
Inefficacy        0
KnowlTrans        1
KnowlMgmt         0
Flu              36
dtype: int64

In [5]:
d1['Flu'].fillna(value=0.0,inplace=True)
d1['KnowlTrans'].fillna(value=np.mean(d1['KnowlTrans']),inplace=True)

In [6]:
x=d1[['Vaccin','HndWshQual','HndWshFreq','SociDist','NoFaceContact','RespEttiqu','PersnDist','HandSanit','Risk','Inefficacy','KnowlTrans','KnowlMgmt']]
y=d1[['Flu']]

In [11]:
s=x.shape[0] 
m=x.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
#calling the logistic regression function
parameters=logisticregression(x,y,lr,parameters,iters,s)

In [10]:
#calling the performance function
performance(x,y,d1,parameters,s)

confusion matrix
[[100 232]
 [  7  71]]
accuracy
0.4170731707317073
precision
0.23432343234323433
recall
0.9102564102564102


In [13]:
f1=d1[['Risk']]
s=f1.shape[0]
m=f1.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f1,y,lr,parameters,iters,s)
performance(f1,y,d1,parameters,s)

confusion matrix
[[308  24]
 [ 57  21]]
accuracy
0.802439024390244
precision
0.4666666666666667
recall
0.2692307692307692


In [16]:
f2=d1[['Risk','HndWshFreq']]
s=f2.shape[0]
m=f2.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f2,y,lr,parameters,iters,s)
performance(f2,y,d1,parameters,s)

confusion matrix
[[317  15]
 [ 67  11]]
accuracy
0.8
precision
0.4230769230769231
recall
0.14102564102564102


In [17]:
f3=d1[['Risk','HndWshQual','HndWshFreq']]
s=f3.shape[0]
m=f3.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f3,y,lr,parameters,iters,s)
performance(f3,y,d1,parameters,s)

confusion matrix
[[320  12]
 [ 68  10]]
accuracy
0.8048780487804879
precision
0.45454545454545453
recall
0.1282051282051282


In [19]:
f4=d1[['Risk','HndWshQual','HndWshFreq','SociDist']]
s=f4.shape[0]
m=f4.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f4,y,lr,parameters,iters,s)
performance(f4,y,d1,parameters,s)

confusion matrix
[[295  37]
 [ 52  26]]
accuracy
0.7829268292682927
precision
0.4126984126984127
recall
0.3333333333333333


In [20]:
f5=d1[['Risk','HndWshQual','HndWshFreq','SociDist','NoFaceContact']]
s=f5.shape[0]
m=f5.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f5,y,lr,parameters,iters,s)
performance(f5,y,d1,parameters,s)

confusion matrix
[[204 128]
 [ 25  53]]
accuracy
0.6268292682926829
precision
0.292817679558011
recall
0.6794871794871795


In [23]:
f6=d1[['Risk','HndWshQual','HndWshFreq','SociDist','NoFaceContact','RespEttiqu']]
s=f6.shape[0]
m=f6.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f6,y,lr,parameters,iters,s)
performance(f6,y,d1,parameters,s)

confusion matrix
[[194 138]
 [ 24  54]]
accuracy
0.6048780487804878
precision
0.28125
recall
0.6923076923076923


In [24]:
f7=d1[['Risk','HndWshQual','HndWshFreq','SociDist','NoFaceContact','RespEttiqu','PersnDist']]
s=f7.shape[0]
m=f7.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f7,y,lr,parameters,iters,s)
performance(f7,y,d1,parameters,s)

confusion matrix
[[ 58 274]
 [  4  74]]
accuracy
0.32195121951219513
precision
0.21264367816091953
recall
0.9487179487179487


In [25]:
f8=d1[['Risk','HndWshQual','HndWshFreq','SociDist','NoFaceContact','RespEttiqu','PersnDist','HandSanit']]
s=f8.shape[0]
m=f8.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f8,y,lr,parameters,iters,s)
performance(f8,y,d1,parameters,s)

confusion matrix
[[ 41 291]
 [  1  77]]
accuracy
0.28780487804878047
precision
0.20923913043478262
recall
0.9871794871794872


In [26]:
f9=d1[['Vaccin','HndWshQual','HndWshFreq','SociDist','NoFaceContact','RespEttiqu','PersnDist','HandSanit','Risk']]
s=f9.shape[0]
m=f9.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f9,y,lr,parameters,iters,s)
performance(f9,y,d1,parameters,s)

confusion matrix
[[ 70 262]
 [  2  76]]
accuracy
0.35609756097560974
precision
0.22485207100591717
recall
0.9743589743589743


In [27]:
f10=d1[['Vaccin','HndWshQual','HndWshFreq','SociDist','NoFaceContact','RespEttiqu','PersnDist','HandSanit','Risk','Inefficacy']]
s=f10.shape[0]
m=f10.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f10,y,lr,parameters,iters,s)
performance(f10,y,d1,parameters,s)

confusion matrix
[[150 182]
 [ 11  67]]
accuracy
0.5292682926829269
precision
0.26907630522088355
recall
0.8589743589743589


In [28]:
f11=d1[['Vaccin','HndWshQual','HndWshFreq','SociDist','NoFaceContact','RespEttiqu','PersnDist','HandSanit','Risk','Inefficacy','KnowlTrans']]
s=f11.shape[0]
m=f11.shape[1]
lr=0.1
parameters=np.ones(m)
iters=100
parameters=logisticregression(f11,y,lr,parameters,iters,s)
performance(f11,y,d1,parameters,s)

confusion matrix
[[100 232]
 [  6  72]]
accuracy
0.4195121951219512
precision
0.23684210526315788
recall
0.9230769230769231
